### ISSUE TITLE
Cant install pulse2percept from source or normal[BUG]

### ISSUE THREAD

**Issue by Nykzom** [pulse2percept/pulse2percept#548]
**Describe the bug**
tried to install pulse2percept in vscode. Made a venv and installed numpy. Than tried to install pulse2percept but dosnt work. Than tried to build it from source, but got the same ERROR-Message (see below) 

**To Reproduce**
1. Open Folder in Vs code
2. cd pulse2percept 
3. pip install -e .

**Error**

```bash
pulse2percept git:(master) pip install -e .
Obtaining file:///Users/*****/Desktop/sensormonito/pulse2percept
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-cgaj4uez/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 450, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-cgaj4uez/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-cgaj4uez/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-cgaj4uez/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-cgaj4uez/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 318, in <module>
        File "<string>", line 253, in setup_package
        File "<string>", line 122, in openmp_build_ext
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**System specifications (please complete the following information):**
- OS: [macOS 13.2.1 | M1]
- Python version: [3.11.3]
- pulse2percept version: [latest]

**Additional context**
When i try to run pulse2percept in Google Colab it works, but i need it to work in Vscode oder Pycharm. Tried for two days now and dont know how to get it running.

**Comment by mbeyeler** [comment]
Hi! I'm not sure this is a problem with p2p. The error says "No module named numpy", so it looks like something went wrong with your NumPy installation. You might want to debug that first:
* Does `python -c 'import numpy'` give you an error?
* What does `which numpy` say where it is installed? Is that installation location part of the `PATH` variable?

Once NumPy is found on the `PATH`, p2p should install correctly.

**Comment by Nykzom** [comment]
Hey, thanks for your fast answer!

> Does python -c 'import numpy' give you an error?

No, there is no Error

> What does which numpy say where it is installed? Is that installation location part of the PATH variable?

```bash
(sensormonitor) ➜  sensormonitor which numpy
numpy not found
(sensormonitor) ➜  sensormonitor pip show numpy
Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: 
Required-by: scipy
(sensormonitor) ➜  sensormonitor export PYTHONPATH=$PYTHONPATH:/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages

(sensormonitor) ➜  sensormonitor pip install pulse2percept
Collecting pulse2percept
  Using cached pulse2percept-0.8.0.tar.gz (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-s73ew12h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-s73ew12h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-s73ew12h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/bq/1yg3b4896h1dgcl9p04xbzw40000gn/T/pip-build-env-s73ew12h/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 318, in <module>
        File "<string>", line 253, in setup_package
        File "<string>", line 122, in openmp_build_ext
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(sensormonitor) ➜  sensormonitor 
```

I dont know whats the problem, but I think there is a problem with my python/numpy installation. I tried like everthing, but doesn't get it to work. 

Here is the Path 

```bash
(sensormonitor) ➜  sensormonitor ls /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Cython                      numpy-1.24.3.dist-info
Cython-0.29.35.dist-info    pip
README.txt                  pip-23.1.2.dist-info
__pycache__                 pkg_resources
_distutils_hack             pyximport
certifi                     scipy
certifi-2023.5.7.dist-info  scipy-1.10.1.dist-info
cython.py                   setuptools
distutils-precedence.pth    setuptools-65.5.0.dist-info
numpy
(sensormonitor) ➜  sensormonitor 
```

**Comment by tallyhawley** [comment]
Hi! It looks like there's a mismatch with your package installation paths.
If you run `which pip` and `which python` (with your venv activated) what do these return?

**Comment by Nykzom** [comment]
>If you run which pip and which python (with your venv activated) what do these return? What about echo $PATH?

```bash
➜  sensormonitor which pip3
/Library/Frameworks/Python.framework/Versions/3.11/bin/pip3
➜  sensormonitor which python
/usr/local/bin/python
➜  sensormonitor echo $PATH
/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin
➜  sensormonitor 
```

**Comment by tallyhawley** [comment]
Hmm... I'm not sure what the issue could be. This doesn't seem to be an issue necessarily with pulse2percept.
It seems you have both Homebrew Python (`/usr/local/bin/python`) and the official Python install from their website (`.../Python.framework/Versions/3.11/bin/python`), and this _might_ be causing the conflict.
It does look like there's a mismatch between your python directory & your pip directory, but I'm not sure if this would affect pip/setuptools. Try using `python -m pip install [package]` instead of `pip3 install [package]`? 
FWIW, Homebrew Python's site packages dir is at `/usr/local/lib/python3.11/site-packages`. 
Also, on Python 3.11, pulse2percept can only be installed using the source code and `pip install -e .`, and not `pip install pulse2percept`. (This won't fix the numpy import problem, but I did some testing locally and even if numpy is found the install will fail on python3.11 unless you are installing from source code.)

**Comment by Nykzom** [comment]
Hey, i tried to install it via source code, but got the same error. I used Pycharm and VSCode but on both i dont get it running. I have to use the module for a homework. But i think i will go back to Google Colab and use it there. So i think we can close this issue. 

Thanks alot for your time and help! (:

**Comment by tallyhawley** [comment]
I'm glad you were able to get it installed!
Yes, there seem to be issues with scikit-image/imageio in pulse2percept's ImageStimulus module right now. I'll open an issue for it.
